data_dir: data
test_glob: ${data_dir}/test/test_*.parquet
user_features: ${data_dir}/user_features.parquet
restaurant_features: ${data_dir}/restaurant_features.parquet
model_path: ${data_dir}/model.pt
scaler_path: ${data_dir}/scaler.npz

batch_size: 128